[package]
name = "goodgame-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.17.0"
hex-literal = "0.3.4"
log = "0.4.17"
env_logger = "0.9.0"
database = { path = "db" }
tokio = { version = "1.2.0", features = ["full"] }

[[bin]]
path = "oracle/main.rs"
name = "oracle"