[package]
name = "oracle_data"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
riven = { version = "1.10.3" }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["test-util", "macros"] }