[package]
name = "oracle_data"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
riven = { version = "1.10.3" }
thiserror = "1.0.33"
log = "0.4.17"
kv = "0.24.0"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["test-util", "macros"] }
dotenv = "0.15.0"
