[package]
name = "database"
version = "0.1.0"

[dependencies]
diesel = { version = "1.4.8", features = ["postgres"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
diesel_cli = "1.4.1"