//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use std::sync::Arc;
use async_once::AsyncOnce;
use sea_orm::DatabaseConnection;
use lazy_static::lazy_static;

pub mod prelude;
pub mod event;
mod conn;

pub use conn::establish_connection;

lazy_static!{
    pub static ref CONNECTION: AsyncOnce<Arc<DatabaseConnection>> = AsyncOnce::new(async {
        Arc::new(establish_connection().await.unwrap())
    });
}
